spring:
  application:
    name: moonce-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.32.234:8848

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"
