spring:
  application:
    name: moonce-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 117.72.32.234:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 117.72.32.234:8080
feign:
  sentinel:
    enabled: true

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
